#!/bin/bash
DATE=$(date +%F-%H%M)
BACKUP_DIR="/opt/dmf7/backups"

mkdir -p $BACKUP_DIR

tar -czf $BACKUP_DIR/dmf7-$DATE.tar.gz /root/DMF7 /opt/dmf7/data

echo "Backup created:"
ls -lh $BACKUP_DIR | tail
